const GET_GAMES="GET_GAMES";
const GET_BY_NAME = "GET_BY_NAME";
const GET_GENRES="GET_GENRES";
const SET_CURRENT_PAGE="SET_CURRENT_PAGE";

const  FILTER_GENRES = "FILTER_GENRES";
const GET_GAMES_BY_ID = "GET_GAMES_BY_ID";
const FILTER_RATING ="FILTER_RATING";
    
const FILTER_ALPHABETIC ="FILTER_ALPHABETIC";
const DISPLAY_STATE = "DISPLAY_STATE";
const GET_GAMES_API ="GET_GAMES_API";
const RESET_FILTERS="RESET_FILTERS";
const GET_GAMES_CREATE ="GET_GAMES_CREATE";
const REST_BY_ID = "REST_BY_ID ";


module.exports= {
    GET_GAMES,
    GET_GENRES,
    SET_CURRENT_PAGE,
    GET_BY_NAME,
    FILTER_GENRES,
    FILTER_RATING,
    FILTER_ALPHABETIC,
    DISPLAY_STATE,
    GET_GAMES_API,
    GET_GAMES_CREATE,
    RESET_FILTERS,
    GET_GAMES_BY_ID,
    REST_BY_ID
}